### ISSUE TITLE
Ipinfodb

### ISSUE THREAD

**Issue by darvidor** [lanmaster53/recon-ng-modules#71]
**Module Name**
Which module is affected?
https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/recon/hosts-hosts/ipinfodb
**Bug Description**
After add a API KEY and run the module, the module reports an error or too much queries per second. Run the module using verbosity 2 and looks like the module doesn't catch the api key properly. See below: URL Didn't contains the KEY. KEy is NONE.
========================= REQUEST =========================
url:    http://api.ipinfodb.com/v3/ip-city/?key=None&ip=52.97.133.184&format=json
method: GET /v3/ip-city/?key=None&ip=52.97.133.184&format=json
header: User-Agent: Recon-ng/v5
header: Accept-Encoding: gzip, deflate
header: Accept: */*
header: Connection: keep-alive
[*] ========================= RESPONSE =========================
status: 200 OK
header: Server: nginx
header: Date: Thu, 10 Oct 2019 08:14:52 GMT
header: Content-Type: application/json; charset=UTF-8
header: Content-Length: 252
header: Connection: keep-alive
header: Access-Control-Allow-Origin: *
body:   b'{\n\t"statusCode" : "ERROR",\n\t"statusMessage" : "Invalid API key.",\n\t"ipAddress" : "52.97.133.184",\n\t"countryCode" : "",\n\t"countryName" : "",\n\t"regionName" : "",\n\t"cityName" : "",\n\t"zipCode" : "",\n\t"latitude" : "0",\n\t"longitude" : "0",\n\t"timeZone" : ""\n}'

**Steps to Reproduce**
\[Steps to reproduce the behavior:
1. Key add ipinfodb_api <mykey>
2. modules load ipinfodb
3. workspaces select <myworkspace> <=== it contains a previous host recon.
4. run

**Expected Behavior**
Just fill the host table with geo info.

**Screenshots**
\[If applicable, screenshots to help explain the problem.\]

**Additional Context**
\[Any other context about the problem.\]

**Comment by rogermanich** [comment]
Hi, 
I tried again and looks like ok now. Maybe the steps are important. Not sure.

**Comment by lanmaster53** [comment]
I seem to recall some folks saying that they had to reload the framework or module for newly added keys to take affect. If you can confirm that was the issue, please let me know.

**Comment by lanmaster53** [comment]
Yes, i just confirmed. Keys are loaded with the module. When you add a new key, you must reload the module. Which is likely what you did to make it work.

**Comment by rogermanich** [comment]
Got it. Thanks
